plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'web/**/*'
    - 'bin/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'api/app.rb'
    - 'random_data_generator.gemspec'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 200

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4
